// featured_stay バッチ6（2026-07-30 Web実在・送迎確認済み）
// 古里温泉(桜島)は主要宿が予約不能状態のためスキップ。
export default {
  'totsukawa-2': {
    name: '湖泉閣 吉乃屋',
    catchcopy: '大正13年創業。二津野湖に臨む全室湖側の源泉かけ流し宿',
    hasShuttle: false,
    accessStation: '大和八木駅からバス約240分「十津川温泉」下車',
  },
  'yuwaku-onsen': {
    name: 'あたらしや',
    catchcopy: '創業250年・1日8組。金沢の奥座敷に息づく純和風の老舗',
    hasShuttle: false,
    accessStation: '金沢駅からバス（湯涌温泉終点）',
  },
  'oyu-onsen-akita': {
    name: '龍門亭 千葉旅館',
    catchcopy: '明治2年創業。四季の庭園と源泉かけ流しの老舗',
    jalanUrl: 'https://www.jalan.net/yad300539/',
    hasShuttle: true,
    shuttleInfo: '最寄駅・バス停から無料送迎あり（2名以上）',
    accessStation: '鹿角花輪駅からバス',
  },
  'isawa-onsen': {
    name: '銘石の宿 かげつ',
    catchcopy: '5000坪の庭園に銘石と20の滝。旅館100選45年連続の名宿',
    jalanUrl: 'https://www.jalan.net/yad327951/',
    hasShuttle: true,
    shuttleInfo: '石和温泉駅北口から無料送迎あり（14〜18時・要連絡）',
    accessStation: '石和温泉駅',
  },
  'kawaji-onsen': {
    name: '湯けむりの里 柏屋',
    catchcopy: '大正15年創業。鬼怒川と男鹿川の合流点に立つ風呂自慢の宿',
    image: '/images/stays/kawaji-onsen.jpg',
    jalanUrl: 'https://www.jalan.net/yad309059/',
    hasShuttle: true,
    shuttleInfo: '川治湯元駅から無料送迎あり（要連絡）',
    accessStation: '川治湯元駅',
  },
  'yunogo': {
    name: '季譜の里',
    catchcopy: '全館畳敷きと76の活け花が迎える美作三湯の宿',
    jalanUrl: 'https://www.jalan.net/yad316820/',
    hasShuttle: false,
    accessStation: '林野駅から車約7分',
  },
  'chikugogawa': {
    name: '泰泉閣',
    catchcopy: '筑後川畔・110余年の湯宿。名物「ジャングル風呂」で知られる',
    jalanUrl: 'https://www.jalan.net/yad323391/',
    hasShuttle: false,
    accessStation: '筑後吉井駅から車約10分',
  },
  'shirahama': {
    name: '紀州・白浜温泉 むさし',
    catchcopy: '白良浜まで徒歩1分。自家源泉ふたつを持つ和風旅館',
    jalanUrl: 'https://www.jalan.net/yad351500/',
    hasShuttle: true,
    shuttleInfo: '白浜駅から旅館組合の無料シャトルあり（迎えは予約不要）',
    accessStation: '白浜駅',
  },
  'nichinan-onsen': {
    name: 'べっぴんの湯の宿 丸新荘',
    catchcopy: 'とろみの強い「べっぴんの湯」を掛け流す日南の湯宿',
    image: '/images/stays/nichinan-onsen.jpg',
    jalanUrl: 'https://www.jalan.net/yad326520/',
    hasShuttle: false,
    accessStation: '北郷駅から車約5分',
  },
  'toyama-himi-2': {
    name: '延楽',
    catchcopy: '黒部峡谷の絶景と美術品コレクションで知られる老舗',
    hasShuttle: true,
    shuttleInfo: '黒部宇奈月温泉駅から送迎あり（前日20時までに要予約）',
    accessStation: '宇奈月温泉駅から徒歩圏',
  },
  'yunokami-onsen': {
    name: '藤龍館',
    catchcopy: '大川渓谷沿い全12室。全室に源泉かけ流しの湯を備える隠れ宿',
    jalanUrl: 'https://www.jalan.net/yad318536/',
    hasShuttle: true,
    shuttleInfo: '新白河駅から無料送迎バスあり（1日1本・約1時間）',
    accessStation: '湯野上温泉駅から徒歩約7分',
  },
};
