// featured_stay バッチ1（2026-07-30 Web実在・送迎確認済み）
// 送迎は確認できた場合のみ記載。加賀屋(和倉)は震災休業中(2027年度末再開目標)のためスキップ。
export default {
  'kusatsu-onsen': {
    name: '奈良屋',
    catchcopy: '明治10年創業。湯畑まで徒歩1分、白旗源泉の湯守の宿',
    image: '/images/stays/kusatsu-onsen.jpg',
    rakutenUrl: 'https://travel.rakuten.co.jp/HOTEL/70807/70807.html',
    jalanUrl: 'https://www.jalan.net/yad362465/',
    hasShuttle: true,
    shuttleInfo: '草津温泉バスターミナルから送迎あり（到着後連絡）',
    accessStation: '長野原草津口駅からバス約25分',
  },
  'arima-onsen': {
    name: '陶泉 御所坊',
    catchcopy: '建久2年（1191）創業と伝わる有馬最古の宿。谷崎潤一郎も愛した',
    image: null,
    jalanUrl: 'https://www.jalan.net/yad382371/',
    hasShuttle: false,
    accessStation: '有馬温泉駅から徒歩約5分',
  },
  'gero-onsen': {
    name: '湯之島館',
    catchcopy: '昭和6年築・国登録有形文化財。5万坪の山中に佇む木造三階の名宿',
    image: '/images/stays/gero-onsen.jpg',
    hasShuttle: true,
    shuttleInfo: '下呂駅から無料送迎あり（13:35〜17:25）',
    accessStation: '下呂駅',
  },
  'shibu-onsen': {
    name: '歴史の宿 金具屋',
    catchcopy: '昭和11年築の木造四階「斉月楼」は国登録有形文化財',
    image: '/images/stays/shibu-onsen.jpg',
    hasShuttle: true,
    shuttleInfo: '湯田中駅から送迎あり（15時以降・要予約）',
    accessStation: '湯田中駅',
  },
  'misasa-onsen': {
    name: '旅館大橋',
    catchcopy: '昭和7年築・ほぼ全館が国登録有形文化財。天然岩風呂の湯宿',
    image: null,
    rakutenUrl: 'https://travel.rakuten.co.jp/HOTEL/40046/40046.html',
    jalanUrl: 'https://www.jalan.net/yad345546/',
    hasShuttle: true,
    shuttleInfo: '倉吉駅から送迎あり（マイクロバス）',
    accessStation: '倉吉駅',
  },
  'naruko-onsen': {
    name: 'ゆさや旅館',
    catchcopy: '寛永9年から約390年、伊達家の湯守を務めた「うなぎ湯」の宿',
    image: null,
    jalanUrl: 'https://www.jalan.net/yad316351/',
    hasShuttle: false,
    accessStation: '鳴子温泉駅から徒歩約4分',
  },
  'bessho-onsen': {
    name: '旅館花屋',
    catchcopy: '大正6年創業。宮大工の技が息づく国登録有形文化財の宿',
    image: null,
    jalanUrl: 'https://www.jalan.net/yad348992/',
    hasShuttle: false,
    accessStation: '別所温泉駅から徒歩約5分',
  },
  'ureshino-onsen': {
    name: '大正屋',
    catchcopy: '大正14年創業。「日本三大美肌の湯」嬉野を代表する老舗',
    image: null,
    jalanUrl: 'https://www.jalan.net/yad321819/',
    hasShuttle: true,
    shuttleInfo: '嬉野温泉駅・嬉野バスセンターから送迎あり（2名以上）',
    accessStation: '嬉野温泉駅',
  },
  'unzen2': {
    name: '雲仙観光ホテル',
    catchcopy: '昭和10年築・国登録有形文化財のクラシックホテル',
    image: '/images/stays/unzen2.jpg',
    hasShuttle: true,
    shuttleInfo: '諫早駅・長崎空港から無料シャトルあり（約1時間）',
    accessStation: '諫早駅',
  },
  'yuda-onsen': {
    name: '松田屋ホテル',
    catchcopy: '延宝3年（1675）創業。維新の志士たちが集った湯田最古の宿',
    image: '/images/stays/yuda-onsen.jpg',
    jalanUrl: 'https://www.jalan.net/yad336484/',
    hasShuttle: false,
    accessStation: '湯田温泉駅からタクシー約5分',
  },
};
