// featured_stay バッチ7・最終（gen_系の著名温泉地 2026-07-30 Web実在・送迎確認済み）
export default {
  'gen_北海_登別温泉': {
    name: '第一滝本館',
    catchcopy: '登別最古の老舗。1500坪・35槽の大浴場に5つの泉質が揃う',
    image: '/images/stays/gen_北海_登別温泉.jpg',
    jalanUrl: 'https://www.jalan.net/yad364904/',
    hasShuttle: false,
    accessStation: '登別駅からバス・タクシー約15分',
  },
  'gen_栃木_湯西川温泉': {
    name: '本家伴久',
    catchcopy: '1666年創業・25代続く平家ゆかりの宿。囲炉裏会席とかずら橋',
    jalanUrl: 'https://www.jalan.net/yad373449/',
    hasShuttle: false,
    accessStation: '湯西川温泉駅からバス約20分',
  },
  'gen_北海_養老牛温泉': {
    name: '湯宿だいいち',
    catchcopy: '野鳥の森と渓流に抱かれた道東屈指の人気湯宿',
    jalanUrl: 'https://www.jalan.net/yad300776/',
    hasShuttle: false,
    accessStation: '中標津空港から車約30分',
  },
  'gen_北海_旭岳温泉': {
    name: '湯元 湧駒荘',
    catchcopy: '大雪山の麓、5つの自家源泉をかけ流す秘湯の宿',
    image: '/images/stays/gen_北海_旭岳温泉.jpg',
    jalanUrl: 'https://www.jalan.net/yad341740/',
    hasShuttle: false,
    accessStation: '旭川駅からバス約90分',
  },
  'gen_北海_十勝川温泉': {
    name: '十勝川温泉第一ホテル',
    catchcopy: '世界的にも希少な植物性モール温泉を代表する宿',
    hasShuttle: true,
    shuttleInfo: '帯広駅から無料送迎シャトルあり（前日17時までに要予約）',
    accessStation: '帯広駅',
  },
  'gen_北海_トムラウシ温泉': {
    name: '東大雪荘',
    catchcopy: '大雪山最深部・トムラウシの一軒宿。登山基地としても名高い',
    image: '/images/stays/gen_北海_トムラウシ温泉.jpg',
    jalanUrl: 'https://www.jalan.net/yad307810/',
    hasShuttle: true,
    shuttleInfo: '新得駅から無料送迎あり（要予約・前日当日不可）',
    accessStation: '新得駅から車約60分',
  },
  'gen_栃木_那須温泉郷': {
    name: '那須温泉 山楽',
    catchcopy: '大正12年創業。昭和天皇も訪れた御用邸と同じ湯の名宿',
    jalanUrl: 'https://www.jalan.net/yad306188/',
    hasShuttle: true,
    shuttleInfo: '那須塩原駅西口から無料送迎あり（完全予約制・14:40発）',
    accessStation: '那須塩原駅',
  },
  'gen_群馬_万座温泉': {
    name: '万座温泉 日進舘',
    catchcopy: '標高1800m・日本有数の濃硫黄泉。乳白色の湯の老舗',
    jalanUrl: 'https://www.jalan.net/yad331317/',
    hasShuttle: true,
    shuttleInfo: '万座バスターミナルから送迎あり（約5分）',
    accessStation: '万座鹿沢口駅からバス約40分',
  },
  'gen_青森_蔦温泉': {
    name: '蔦温泉旅館',
    catchcopy: '久安3年（1147）記録の湯治場。ブナの森に立つ一軒宿',
    jalanUrl: 'https://www.jalan.net/yad337770/',
    hasShuttle: true,
    shuttleInfo: '七戸十和田駅から無料送迎あり（15時発・3日前までに要予約）',
    accessStation: '七戸十和田駅',
  },
  'gen_青森_黄金崎不老不死温泉': {
    name: '不老ふ死温泉',
    catchcopy: '波打ち際の黄金色露天で日本海の夕陽に浸る一軒宿',
    jalanUrl: 'https://www.jalan.net/yad323694/',
    hasShuttle: true,
    shuttleInfo: 'ウェスパ椿山駅から送迎あり（要予約）',
    accessStation: 'ウェスパ椿山駅',
  },
};
