// featured_stay バッチ4（2026-07-30 Web実在・送迎確認済み）
export default {
  'tamatsukuri-onsen': {
    name: '湯之助の宿 長楽園',
    catchcopy: '明治元年創業。120坪の混浴大露天「龍宮の湯」を擁する湯之助の宿',
    image: '/images/stays/tamatsukuri-onsen.jpg',
    jalanUrl: 'https://www.jalan.net/yad323049/',
    hasShuttle: true,
    shuttleInfo: '玉造温泉駅からシャトルバスあり',
    accessStation: '玉造温泉駅',
  },
  'okutsu': {
    name: '名泉鍵湯 奥津荘',
    catchcopy: '昭和2年築・国登録有形文化財。足元湧出の「鍵湯」は津山藩主専用だった名湯',
    image: '/images/stays/okutsu.jpg',
    hasShuttle: false,
    accessStation: '津山駅からバス（奥津温泉）',
  },
  'iwaki-spa': {
    name: '古滝屋',
    catchcopy: '元禄8年（1695）創業330年。湯本の湯を守り続ける老舗',
    image: '/images/stays/iwaki-spa.jpg',
    jalanUrl: 'https://www.jalan.net/yad335663/',
    hasShuttle: false,
    accessStation: '湯本駅から徒歩約7分',
  },
  'nozawa-onsen-niigata': {
    name: '雪国の宿 高半',
    catchcopy: '開湯900余年の湯元。川端康成が「雪国」を書いた宿',
    image: '/images/stays/nozawa-onsen-niigata.jpg',
    hasShuttle: true,
    shuttleInfo: '越後湯沢駅から迎えあり（到着後に連絡）',
    accessStation: '越後湯沢駅',
  },
  'hanamaki-onsen': {
    name: '鉛温泉 藤三旅館',
    catchcopy: '昭和16年築の本館と日本一深い岩風呂「白猿の湯」は国登録有形文化財',
    image: '/images/stays/hanamaki-onsen.jpg',
    hasShuttle: true,
    shuttleInfo: '花巻駅・新花巻駅から無料シャトルあり（要予約）',
    accessStation: '花巻駅',
  },
  'yufuin-2': {
    name: '亀の井別荘',
    catchcopy: '大正10年創業。金鱗湖畔一万坪の杜に佇む由布院の御三家',
    hasShuttle: true,
    shuttleInfo: '由布院駅から無料送迎あり（10〜16時・要予約）',
    accessStation: '由布院駅',
  },
  'ibusuki-onsen': {
    name: '指宿白水館',
    catchcopy: '約1000坪の「元禄風呂」と砂むし温泉。薩摩の迎賓の宿',
    jalanUrl: 'https://www.jalan.net/yad357348/',
    hasShuttle: true,
    shuttleInfo: '指宿駅から無料送迎あり（定時運行・予約不要）',
    accessStation: '指宿駅',
  },
  'niigata-spa': {
    name: '白玉の湯 泉慶',
    catchcopy: 'エメラルドグリーンの自家源泉を持つ月岡の代表格',
    hasShuttle: false,
    accessStation: '豊栄駅から車約20分（有料シャトルあり）',
  },
  'hitoyoshi-onsen': {
    name: '人吉旅館',
    catchcopy: '昭和9年築・国登録有形文化財。球磨川水害から蘇った木造宿',
    hasShuttle: false,
    accessStation: '人吉駅から徒歩圏',
  },
  'yubara-onsen': {
    name: '元禄旅籠 油屋',
    catchcopy: '元禄元年（1688）創業。砂湯の湯郷に残る旅籠建築',
    image: '/images/stays/yubara-onsen.jpg',
    jalanUrl: 'https://www.jalan.net/yad323331/',
    hasShuttle: true,
    shuttleInfo: '湯原温泉バス停から送迎あり',
    accessStation: '中国勝山駅からバス約49分',
  },
};
