// featured_stay バッチ2（2026-07-30 Web実在・送迎確認済み）
export default {
  'nozawa-onsen': {
    name: '村のホテル 住吉屋',
    catchcopy: '明治2年創業。名所「麻釜」の畔に立つ1日10組の湯宿',
    jalanUrl: 'https://www.jalan.net/yad344455/',
    hasShuttle: false,
    accessStation: '野沢温泉バス停から徒歩圏（麻釜そば）',
  },
  'sakunami-onsen': {
    name: '伝承千年の宿 佐勘',
    catchcopy: '伊達政宗公の湯浴み御殿。代々湯守を務める秋保の名門',
    image: '/images/stays/sakunami-onsen.jpg',
    jalanUrl: 'https://www.jalan.net/yad318193/',
    hasShuttle: true,
    shuttleInfo: '仙台駅東口から無料送迎バスあり（予約定員制）',
    accessStation: '仙台駅',
  },
  'shiobara-onsen': {
    name: '明賀屋本館',
    catchcopy: '1674年創業。88段の階段を下りた先に川岸露天が待つ秘湯宿',
    jalanUrl: 'https://www.jalan.net/yad303687/',
    hasShuttle: true,
    shuttleInfo: '塩釜バス停から無料送迎あり',
    accessStation: '西那須野駅からバス',
  },
  'kinugawa-onsen': {
    name: 'あさやホテル',
    catchcopy: '明治21年創業。鬼怒川を代表する老舗の大型温泉ホテル',
    image: '/images/stays/kinugawa-onsen.jpg',
    hasShuttle: true,
    shuttleInfo: '宇都宮駅から送迎バスあり（要予約）',
    accessStation: '鬼怒川温泉駅からダイヤルバス約8分',
  },
  'okuhida-onsen': {
    name: '槍見の湯 槍見舘',
    catchcopy: '槍ヶ岳を望む蒲田川沿いの古民家造りの一軒宿',
    jalanUrl: 'https://www.jalan.net/yad322143/',
    hasShuttle: false,
    accessStation: '新穂高温泉（高山駅からバス）',
  },
  'dorogawa-onsen': {
    name: '花屋徳兵衛',
    catchcopy: '創業500年・洞川温泉最古。修験の宿場に立つ十七代続く宿',
    jalanUrl: 'https://www.jalan.net/yad343142/',
    hasShuttle: true,
    shuttleInfo: '洞川温泉バス停から迎えあり（要連絡）',
    accessStation: '下市口駅からバス約80分',
  },
  'yugawara-onsen': {
    name: '伊藤屋',
    catchcopy: '明治21年創業・国登録有形文化財。島崎藤村ゆかりの宿',
    hasShuttle: false,
    accessStation: '湯河原駅からバス（万葉公園入口）',
  },
  'takarakawa-onsen': {
    name: '宝川温泉 汪泉閣',
    catchcopy: '延べ470畳の大露天風呂。渓流沿いの秘湯一軒宿',
    image: '/images/stays/takarakawa-onsen.jpg',
    jalanUrl: 'https://www.jalan.net/yad312746/',
    hasShuttle: true,
    shuttleInfo: '水上駅から送迎バスあり（約35分）',
    accessStation: '水上駅',
  },
  'zaou-onsen': {
    name: '深山荘 高見屋',
    catchcopy: '享保元年（1716）創業。高湯通りの高台に立つ蔵王の老舗',
    jalanUrl: 'https://www.jalan.net/yad321744/',
    hasShuttle: false,
    accessStation: '蔵王温泉バスターミナルから徒歩約5分',
  },
  'kaga-onsen': {
    name: '白鷺湯たわらや',
    catchcopy: '鎌倉期「湯元十二軒」の流れをくむ創業800年の宿',
    jalanUrl: 'https://www.jalan.net/yad317168/',
    hasShuttle: true,
    shuttleInfo: '加賀温泉駅から無料送迎バスあり（約20分・事前予約）',
    accessStation: '加賀温泉駅',
  },
};
