// featured_stay 全国展開バッチ1（2026-08-01 Web実在・送迎確認済み）
export default {
  'nikko': {
    name: '日光金谷ホテル',
    catchcopy: '1873年創業・現存する日本最古のリゾートクラシックホテル',
    image: '/images/stays/nikko.jpg',
    hasShuttle: true,
    shuttleInfo: '東武日光駅から無料シャトルあり（定時運行）',
    accessStation: '東武日光駅',
  },
  'karuizawa': {
    name: '万平ホテル',
    catchcopy: '1894年創業。ジョン・レノンも愛した軽井沢クラシックの象徴',
    image: '/images/stays/karuizawa.jpg',
    hasShuttle: true,
    shuttleInfo: '軽井沢駅から宿泊者送迎バスあり（要予約）',
    accessStation: '軽井沢駅',
  },
  'nara': {
    name: '奈良ホテル',
    catchcopy: '1909年創業「関西の迎賓館」。辰野金吾設計の桃山御殿風建築',
    image: '/images/stays/nara.jpg',
    hasShuttle: true,
    shuttleInfo: '近鉄奈良駅への送迎バスあり',
    accessStation: '近鉄奈良駅からタクシー約5分',
  },
  'miyajima': {
    name: 'みやじまの宿 岩惣',
    catchcopy: '安政元年創業。もみじ谷に佇むG7晩餐会場にもなった名旅館',
    hasShuttle: true,
    shuttleInfo: '宮島桟橋から送迎あり（要事前連絡）',
    accessStation: '宮島桟橋から徒歩約15分',
  },
  'hakone': {
    name: '富士屋ホテル',
    catchcopy: '1878年開業・日本初の本格リゾートホテル。花御殿と大食堂は必見',
    image: '/images/stays/hakone.jpg',
    jalanUrl: 'https://www.jalan.net/yad325862/',
    hasShuttle: true,
    shuttleInfo: '宮ノ下駅から迎えあり（到着後に連絡）',
    accessStation: '宮ノ下駅から徒歩約7分',
  },
  'kurashiki-o': {
    name: '旅館くらしき',
    catchcopy: '美観地区の中心、江戸期の砂糖問屋を改装した8室の料理旅館',
    hasShuttle: false,
    accessStation: '倉敷駅から徒歩約15分（美観地区内）',
  },
  'kamakura': {
    name: 'かいひん荘鎌倉',
    catchcopy: '大正13年築の洋館は国登録有形文化財。由比ヶ浜の割烹旅館',
    image: '/images/stays/kamakura.jpg',
    jalanUrl: 'https://www.jalan.net/yad310363/',
    hasShuttle: false,
    accessStation: '由比ヶ浜駅から徒歩約1分',
  },
  'takayama-o': {
    name: '本陣平野屋 花兆庵',
    catchcopy: '古い町並まで徒歩1分。「100のおもてなし」の宿',
    jalanUrl: 'https://www.jalan.net/yad330857/',
    hasShuttle: true,
    shuttleInfo: '高山駅から送迎あり（到着時間に合わせて迎え）',
    accessStation: '高山駅から徒歩約10分',
  },
  'ise': {
    name: '麻吉旅館',
    catchcopy: '創業200余年・木造五層の懸崖造。遊郭建築が今も生きる文化財の宿',
    image: '/images/stays/ise.jpg',
    hasShuttle: false,
    accessStation: '近鉄宇治山田駅からタクシー約5分',
  },
  'atami': {
    name: '熱海 大観荘',
    catchcopy: '横山大観ゆかりの数寄屋の名宿。相模灘を望む高台に立つ',
    jalanUrl: 'https://www.jalan.net/yad326876/',
    hasShuttle: true,
    shuttleInfo: '熱海駅から定時送迎あり（予約不要・13:45〜16:45）',
    accessStation: '熱海駅',
  },
};
