// featured_stay 全国展開バッチ2（2026-08-01 Web実在・送迎確認済み）
export default {
  'otaru': {
    name: '料亭湯宿 銀鱗荘',
    catchcopy: '明治6年築の鰊御殿を移築。小樽を見下ろす高台の文化財宿',
    image: '/images/stays/otaru.jpg',
    jalanUrl: 'https://www.jalan.net/yad335042/',
    hasShuttle: true,
    shuttleInfo: '小樽築港駅から無料送迎あり（15〜18時）',
    accessStation: '小樽築港駅',
  },
  'hagi': {
    name: '萩城三の丸 北門屋敷',
    catchcopy: '毛利屋敷跡・世界遺産の城下町に立つ格式の宿',
    hasShuttle: false,
    accessStation: '萩循環まぁーるバス「北門屋敷入口」下車',
  },
  'aizu': {
    name: '向瀧',
    catchcopy: '国の登録有形文化財第1号。会津藩指定保養所の流れをくむ木造宿',
    image: '/images/stays/aizu.jpg',
    hasShuttle: false,
    accessStation: '会津若松駅から周遊バス約15分「東山温泉駅」下車',
  },
  'kakunodate': {
    name: '角館山荘 侘桜',
    catchcopy: '築200年の茅葺古民家を移築。全室かけ流し・野﨑洋光監修の食',
    hasShuttle: true,
    shuttleInfo: '角館駅から送迎あり（要予約）',
    accessStation: '角館駅から車約15分',
  },
  'shodoshima': {
    name: '島宿真里',
    catchcopy: '醤の郷に佇む7室の宿。「醤油会席」で島の発酵文化を味わう',
    hasShuttle: true,
    shuttleInfo: '池田港から送迎あり',
    accessStation: '池田港',
  },
  'onomichi': {
    name: 'Ryokan 尾道西山（西山別館）',
    catchcopy: '文豪が愛した1943年創業の離れの宿。芝庭の先に瀬戸内が広がる',
    image: '/images/stays/onomichi.jpg',
    jalanUrl: 'https://www.jalan.net/yad305831/',
    hasShuttle: false,
    accessStation: '尾道駅から車約10分',
  },
  'naoshima': {
    name: 'ベネッセハウス',
    catchcopy: '安藤忠雄設計・美術館に泊まる。23時まで作品鑑賞できる特権も',
    image: '/images/stays/naoshima.jpg',
    hasShuttle: true,
    shuttleInfo: '宮浦港から宿泊者専用送迎バスあり',
    accessStation: '宮浦港',
  },
  'yufuin': {
    name: '由布院 玉の湯',
    catchcopy: '「西の玉の湯」と称される御三家。雑木林の離れで過ごす静寂',
    hasShuttle: false,
    accessStation: '由布院駅から徒歩約15分',
  },
  'yakushima': {
    name: 'sankara hotel&spa 屋久島',
    catchcopy: '世界遺産の森を望むオーベルジュ型リゾートの最高峰',
    jalanUrl: 'https://www.jalan.net/yad386188/',
    hasShuttle: true,
    shuttleInfo: '屋久島空港から送迎あり',
    accessStation: '屋久島空港',
  },
  'matsushima': {
    name: '小松館 好風亭',
    catchcopy: '松島湾の絶景を独り占めする海辺の宿。露天から島々を望む',
    jalanUrl: 'https://www.jalan.net/yad312115/',
    hasShuttle: true,
    shuttleInfo: '松島海岸駅・松島駅から送迎あり（到着時に連絡）',
    accessStation: '松島海岸駅',
  },
};
